global_costmap:
  global_frame: map
  rolling_window: true # true required for rrt_exploration
  width: 100.0
  height: 100.0
  resolution: 0.05
  track_unknown_space: true
  inflation_layer:
    inflation_radius: 1.0
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: armbot0/armbot_laser_scanner, data_type: LaserScan, topic: /armbot0/armbot_laser_scanner/laser/scan, marking: true, clearing: true}